# .github/workflows/check_website_status.yml
name: Check Website Status

on:
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  check_status:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: pip install requests

    - name: Run website check script
      run: python check_site.py
